config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:registrations]

  root to: "pages#home"

  resources :posts, path: "actualites"

  get "/cabinet", to: "pages#cabinet"

  get "/expertise", to: "pages#expertise"

  get "/equipe", to: "pages#equipe"

  get "/contact", to: "contact#new"
  post "/contact", to: "contact#message"

  get "/liens-utiles", to: "pages#liens_utiles"
  get "/confidentialite", to: "pages#confidentialite"
  get "/mentions-legales", to: "pages#mentions_legales"

  match "/404", to: "errors#not_found", via: :all
  match "/422", to: "errors#unacceptable", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :first_name, :last_name, :fonction, :firm, :subject, presence: true
  # validates :message, presence: true LENGTH
  validates_email_format_of :email, message: "ne semble pas être une adresse valide."
  validates :message, length: { minimum: 10, maximum: 1000, too_short: "doit faire au moins %{count} caractères.", too_long: "doit faire au maximum %{count} caractères." }
end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  has_one_attached :photo
  validates :category, :title, :content, :date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit::Authorization

  # Pundit: allow-list approach
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "Vous n'êtes pas autorisé à effectuer cette action."
    redirect_to(root_path)
  end

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[new message]

  def new
    @contact = Contact.new
    authorize @contact
  end

  def message
    @contact = Contact.new(contact_params)
    authorize @contact
    # Captcha
    @contact.validate # this line will validate the user even if Recaptcha failed. This way we will present all potential validation errors right away
    v3_verify = verify_recaptcha action: 'message', minimum_score: 0.9, secret_key: ENV['RECAPTCHA_SECRET_KEY_V3']
    v2_verify = verify_recaptcha(secret_key: ENV['RECAPTCHA_SECRET_KEY_V2'])

    if (v3_verify || v2_verify) && @contact.valid?
      ContactMailer.with(contact: @contact).contact_admin_email.deliver_now
      ContactMailer.with(contact: @contact).contact_user_email.deliver_now
      redirect_to root_path, notice: "Votre message a bien été envoyé."
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:first_name, :last_name, :fonction, :firm, :email, :phone, :subject, :message)
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    authorize :error, :not_found?

    render status: 404
  end

  def unacceptable
    authorize :error, :unacceptable?

    render status: 422
  end

  def internal_server_error
    authorize :error, :internal_server_error?

    render status: 500
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home
    @posts = Post.order(date: :desc).first(2)
  end

  def cabinet
  end

  def expertise
  end

  def equipe
  end

  def liens_utiles
  end

  def confidentialite
  end

  def mentions_legales
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :set_post, only: %i[show edit update destroy]

  def index
    @posts = filter_posts(policy_scope(Post))
  end

  def show
    authorize @post
  end

  def new
    @post = Post.new
    authorize @post
  end

  def create
    @post = Post.new(post_params)
    authorize @post
    if @post.save
      default_photo(@post) if @post.photo.key.nil?
      redirect_to posts_path, notice: "Actualitée postée 👍"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize @post
  end

  def update
    authorize @post
    if @post.update(post_params.except(:photo))
      if post_params[:photo].present?
        @post.photo.purge
        @post.photo.attach(post_params[:photo])
      end
      redirect_to post_path(@post), notice: "Actualitée modifiée 👍"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @post
    @post.destroy
    redirect_to posts_path, notice: "Actualitée supprimée 👍"
  end

  private

  def filter_posts(posts)
    case params[:catégorie]
    when "classements"
      posts.where(category: "classements").order(date: :desc)
    when "communiqués"
      posts.where(category: "communiqués de presse").order(date: :desc)
    when "événements"
      posts.where(category: "événements").order(date: :desc)
    when "publications"
      posts.where(category: "publications").order(date: :desc)
    else
      posts.order(date: :desc)
    end
  end

  def set_post
    @post = Post.friendly.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:category, :date, :title, :subtitle, :publish_link, :content, :article_link, :photo)
  end

  def default_photo(post)
    post.photo.purge
    default_photo = File.open(File.join(Rails.root,'app/assets/images/actu.jpg'))
    post.photo.attach(io: default_photo, filename: "lsa-actu", content_type: "image/png")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/contact/new.turbo_stream.erb
<%= turbo_stream.replace 'recaptcha' do %>
  <div class="mb-3 row"
    id='recaptchaV2'
    data-controller='recaptcha-v2'
    data-recaptcha-v2-site-key-value="<%= ENV['RECAPTCHA_SITE_KEY_V2'] %>"></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LSAParis</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag "favicon.png", rel: "icon", type: "image/png" %>

    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>">
    <meta property="og:type" content="website">
    <meta property="og:url" content="<%= request.original_url %>">
    <meta property="og:image" content="<%= meta_image %>">
    <meta property="og:description" content="<%= meta_description %>">
    <meta property="og:site_name" content="<%= meta_title %>">

    <!-- Twitter Card data - A AJOUTER UNE FOIS COMPTE TWITTER DU CLIENT RECUPERE -->
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <%# PWA %>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
    <%= render 'shared/ios_pwa_links' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/confidentialite.html.erb
<% content_for :meta_title, "LSA PARIS - Conseil Contentieux Médiation Arbitrage - Confidentialité" %>
<% content_for :meta_description, "RODOLPHE : description Réseaux Sociaux pour la page Confidentialité" %>
<%# Si tu ne veut pas faire une description spécifique, enlève la ligne ci-dessus %>
<%# Et ça sera la meta_description de config/meta.yml qui sera prise en compte %>

<h1>Confidentialité</h1>

app/views/pages/liens_utiles.html.erb
<% content_for :meta_title, "LSA PARIS - Conseil Contentieux Médiation Arbitrage - Liens utiles" %>
<% content_for :meta_description, "RODOLPHE : description Réseaux Sociaux pour la page Liens utiles" %>
<%# Si tu ne veut pas faire une description spécifique, enlève la ligne ci-dessus %>
<%# Et ça sera la meta_description de config/meta.yml qui sera prise en compte %>

<h1>Liens juridiques</h1>

app/views/posts/index.html.erb
<% content_for :meta_title, "LSA PARIS - Conseil Contentieux Médiation Arbitrage - Actualités" %>
<% content_for :meta_description, "RODOLPHE : description Réseaux Sociaux pour la page Actualités" %>

<div class="bg-white">
  <div class="relative isolate px-6 pt-14 lg:px-8">
    <div class="mx-auto max-w-2xl py-8 sm:py-12 lg:py-16">
      <div class="text-center">
        <h1 class="text-4xl font-bold tracking-tight text-gray-900 sm:text-6xl">Nos actualités</h1>
        <p class="mt-6 text-lg leading-8 text-gray-600">Anim aute id magna aliqua ad ad non deserunt sunt. Qui irure qui lorem cupidatat commodo. Elit sunt amet fugiat veniam occaecat fugiat aliqua.</p>
      </div>
    </div>
  </div>
</div>


<main>

  <section id="first-section-actus">
    <h1>Actualités</h1>

    <% if policy(Post).new? %>
      <%= link_to "Nouvelle actualité", new_post_path %>
    <% end %>

    <p>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
      Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
      Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </p>

  </section>

  <section id="filter-actus-categories">
    <%= link_to "TOUS", posts_path %>
    <%= link_to "CLASSEMENTS", posts_path(catégorie: "classements") %>
    <%= link_to "Communiqués de presse".upcase, posts_path(catégorie: "communiqués") %>
    <%= link_to "Evénements".upcase, posts_path(catégorie: "événements") %>
    <%= link_to "PUBLICATIONS", posts_path(catégorie: "publications") %>
  </section>

  <section id="actus-categories">
    <% @posts.each do |post| %>
      <%= link_to post_path(post), class: "text-decoration-none text-black" do %>
        <article class="d-flex my-3 gap-3">
          <%= cl_image_tag post.photo.key, height: 300, width: 400, crop: :fill %>
          <div>
            <h2><%= post.category.upcase %></h2>
            <h4><%= post.date %></h4>
            <h3><%= post.title %></h3>
            <h5><strong><%= post.subtitle %></strong></h5>
            <%# Réduire le nombre de caractères de content pour ne pas avoir la fin ? Ou ajouter une colonne dans le model de Post pour la partie "Voir l'article rédigé par..."  ? %>
            <p><%= post.content %></p>
          </div>
        </article>
      <% end %>
    <% end %>
  </section>

</main>

app/views/posts/show.html.erb
<% content_for :meta_title, "LSA PARIS - Actualités - #{@post.title}" %>
<% content_for :meta_description, @post.content %>
<% content_for :meta_image, cl_image_path(@post.photo.key) if @post.photo.attached? %>

<header>
  <%= link_to "< Retour", :back %>
  <p><%= @post.date %> | <%= "actualités".upcase %> | <%= @post.category.upcase %></p>
</header>

<main>

  <article class="d-flex my-3 gap-3">
    <%= cl_image_tag @post.photo.key, height: 500, width: 500, crop: :fill %>
    <div>
      <h2><%= @post.title %></h2>
      <h4>
        <strong>
          <%# Attention il n'y a pas toujours de subtitle dans un Post %>
          <%= @post.subtitle %>
          <% unless @post.publish_link.nil? || @post.publish_link.empty? %>
            (<%= link_to "Publiée", @post.publish_link, target: "_blank" %>)
          <% end %>
        </strong>
      </h4>
      <p>
        <%= @post.content %>
        <% unless @post.article_link.nil? || @post.article_link.empty? %>
          <%= link_to "lire l'article.", @post.article_link, target: "_blank" %>
        <% end %>
      </p>

      <% if policy(@post).edit? %>
        <%= link_to "Modifier l'actualité", edit_post_path(@post) %>
      <% end %>

      <% if policy(@post).destroy? %>
        <%= link_to "Supprimer l'actualité",
                  post_path(@post),
                  data: {turbo_method: :delete, turbo_confirm: "Supprimer cette actualité ?"} %>
      <% end %>

    </div>
  </article>

</main>

app/views/shared/_footer.html.erb
<footer class="bg-gray-900" aria-labelledby="footer-heading">
  <h2 id="footer-heading" class="sr-only">Footer</h2>
  <div class="mx-auto max-w-7xl px-6 pb-8 pt-16 sm:pt-24 lg:px-8 lg:pt-32">
    <div class="xl:grid xl:grid-cols-3 xl:gap-8">
      <div class="space-y-8">
        <%= image_tag "LSA-PARIS-LOGO.jpg", class:"w-8 h-8" %>
        <p class="text-sm leading-6 text-gray-300">Making the world a better place through constructing elegant hierarchies.</p>
        <div class="flex space-x-6">
          <a href="#" class="text-gray-500 hover:text-gray-400">
            <span class="sr-only">Facebook</span>
            <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
              <path fill-rule="evenodd" d="M22 12c0-5.523-4.477-10-10-10S2 6.477 2 12c0 4.991 3.657 9.128 8.438 9.878v-6.987h-2.54V12h2.54V9.797c0-2.506 1.492-3.89 3.777-3.89 1.094 0 2.238.195 2.238.195v2.46h-1.26c-1.243 0-1.63.771-1.63 1.562V12h2.773l-.443 2.89h-2.33v6.988C18.343 21.128 22 16.991 22 12z" clip-rule="evenodd" />
            </svg>
          </a>
          <a href="#" class="text-gray-500 hover:text-gray-400">
            <span class="sr-only">Instagram</span>
            <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
              <path fill-rule="evenodd" d="M12.315 2c2.43 0 2.784.013 3.808.06 1.064.049 1.791.218 2.427.465a4.902 4.902 0 011.772 1.153 4.902 4.902 0 011.153 1.772c.247.636.416 1.363.465 2.427.048 1.067.06 1.407.06 4.123v.08c0 2.643-.012 2.987-.06 4.043-.049 1.064-.218 1.791-.465 2.427a4.902 4.902 0 01-1.153 1.772 4.902 4.902 0 01-1.772 1.153c-.636.247-1.363.416-2.427.465-1.067.048-1.407.06-4.123.06h-.08c-2.643 0-2.987-.012-4.043-.06-1.064-.049-1.791-.218-2.427-.465a4.902 4.902 0 01-1.772-1.153 4.902 4.902 0 01-1.153-1.772c-.247-.636-.416-1.363-.465-2.427-.047-1.024-.06-1.379-.06-3.808v-.63c0-2.43.013-2.784.06-3.808.049-1.064.218-1.791.465-2.427a4.902 4.902 0 011.153-1.772A4.902 4.902 0 015.45 2.525c.636-.247 1.363-.416 2.427-.465C8.901 2.013 9.256 2 11.685 2h.63zm-.081 1.802h-.468c-2.456 0-2.784.011-3.807.058-.975.045-1.504.207-1.857.344-.467.182-.8.398-1.15.748-.35.35-.566.683-.748 1.15-.137.353-.3.882-.344 1.857-.047 1.023-.058 1.351-.058 3.807v.468c0 2.456.011 2.784.058 3.807.045.975.207 1.504.344 1.857.182.466.399.8.748 1.15.35.35.683.566 1.15.748.353.137.882.3 1.857.344 1.054.048 1.37.058 4.041.058h.08c2.597 0 2.917-.01 3.96-.058.976-.045 1.505-.207 1.858-.344.466-.182.8-.398 1.15-.748.35-.35.566-.683.748-1.15.137-.353.3-.882.344-1.857.048-1.055.058-1.37.058-4.041v-.08c0-2.597-.01-2.917-.058-3.96-.045-.976-.207-1.505-.344-1.858a3.097 3.097 0 00-.748-1.15 3.098 3.098 0 00-1.15-.748c-.353-.137-.882-.3-1.857-.344-1.023-.047-1.351-.058-3.807-.058zM12 6.865a5.135 5.135 0 110 10.27 5.135 5.135 0 010-10.27zm0 1.802a3.333 3.333 0 100 6.666 3.333 3.333 0 000-6.666zm5.338-3.205a1.2 1.2 0 110 2.4 1.2 1.2 0 010-2.4z" clip-rule="evenodd" />
            </svg>
          </a>
          <a href="#" class="text-gray-500 hover:text-gray-400">
            <span class="sr-only">Twitter</span>
            <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
              <path d="M8.29 20.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0022 5.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.072 4.072 0 012.8 9.713v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 012 18.407a11.616 11.616 0 006.29 1.84" />
            </svg>
          </a>
          <a href="#" class="text-gray-500 hover:text-gray-400">
            <span class="sr-only">GitHub</span>
            <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
              <path fill-rule="evenodd" d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z" clip-rule="evenodd" />
            </svg>
          </a>
          <a href="#" class="text-gray-500 hover:text-gray-400">
            <span class="sr-only">YouTube</span>
            <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
              <path fill-rule="evenodd" d="M19.812 5.418c.861.23 1.538.907 1.768 1.768C21.998 8.746 22 12 22 12s0 3.255-.418 4.814a2.504 2.504 0 0 1-1.768 1.768c-1.56.419-7.814.419-7.814.419s-6.255 0-7.814-.419a2.505 2.505 0 0 1-1.768-1.768C2 15.255 2 12 2 12s0-3.255.417-4.814a2.507 2.507 0 0 1 1.768-1.768C5.744 5 11.998 5 11.998 5s6.255 0 7.814.418ZM15.194 12 10 15V9l5.194 3Z" clip-rule="evenodd" />
            </svg>
          </a>
        </div>
      </div>
      <div class="mt-16 grid grid-cols-6 gap-8 xl:col-span-2 xl:mt-0">
        <%= link_to "Actualités", posts_path, class: "nav-link"%>
        <%= link_to "Cabinet", cabinet_path, class: "nav-link"%>
        <%= link_to "Expertise", expertise_path, class: "nav-link"%>
        <%= link_to "Equipe", equipe_path, class: "nav-link"%>
        <%= link_to "Contact", contact_path, class: "nav-link"%>
        <%= link_to "Liens utiles", liens_utiles_path, class: "nav-link px-2"%>
        <%= link_to "Confidentialité", confidentialite_path, class: "nav-link px-2"%>
        <%= link_to "Mentions légales", mentions_legales_path, class: "nav-link px-2"%>
      </div>
    </div>
    <div class="mt-16 border-t border-white/10 pt-8 sm:mt-20 lg:mt-24">
      <p class="text-xs leading-5 text-gray-400">&copy; 2020 Your Company, Inc. All rights reserved.</p>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="bg-white shadow">
  <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
    <div class="relative flex h-16 justify-between">
      <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
        <!-- Mobile menu button -->
        <button type="button" class="relative inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-100 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500" aria-controls="mobile-menu" aria-expanded="false">
          <span class="absolute -inset-0.5"></span>
          <span class="sr-only">Open main menu</span>
          <!--
            Icon when menu is closed.

            Menu open: "hidden", Menu closed: "block"
          -->
          <svg class="block h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
          </svg>
          <!--
            Icon when menu is open.

            Menu open: "block", Menu closed: "hidden"
          -->
          <svg class="hidden h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      <div class="flex flex-1 items-center justify-start">
        <%= link_to root_path, class: "h-8 w-8" do %>
          <%= image_tag "LSA-PARIS-LOGO.jpg" %>
        <% end %>
        
        <div class="hidden sm:ml-6 sm:flex sm:space-x-8">
          <!-- Current: "border-indigo-500 text-gray-900", Default: "border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700" -->
          <%= link_to 'Cabinet', cabinet_path, class: "nav-link" %>
          <%= link_to 'Expertise', expertise_path, class: "nav-link" %>
          <%= link_to 'Equipe', equipe_path, class: "nav-link" %>
          <%= link_to 'Actualités', posts_path, class: "nav-link" %>
        </div>
      </div>
      <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
        <%= link_to 'Contact', contact_path, class: "btn-primary" %>
      </div>
    </div>
  </div>

  <!-- Mobile menu, show/hide based on menu state. -->
  <div class="sm:hidden" id="mobile-menu">
    <div class="space-y-1 pb-4 pt-2">
      <!-- Current: "bg-indigo-50 border-indigo-500 text-indigo-700", Default: "border-transparent text-gray-500 hover:bg-gray-50 hover:border-gray-300 hover:text-gray-700" -->
      <a href="#" class="block border-l-4 border-indigo-500 bg-indigo-50 py-2 pl-3 pr-4 text-base font-medium text-indigo-700">Dashboard</a>
      <a href="#" class="block border-l-4 border-transparent py-2 pl-3 pr-4 text-base font-medium text-gray-500 hover:border-gray-300 hover:bg-gray-50 hover:text-gray-700">Team</a>
      <a href="#" class="block border-l-4 border-transparent py-2 pl-3 pr-4 text-base font-medium text-gray-500 hover:border-gray-300 hover:bg-gray-50 hover:text-gray-700">Projects</a>
      <a href="#" class="block border-l-4 border-transparent py-2 pl-3 pr-4 text-base font-medium text-gray-500 hover:border-gray-300 hover:bg-gray-50 hover:text-gray-700">Calendar</a>
    </div>
  </div>
</nav>
<!-- <nav class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "LSA-PARIS-LOGO.jpg"  %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <%= link_to "Actualités", posts_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Cabinet", cabinet_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Expertise", expertise_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Equipe", equipe_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Contact", contact_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Déconnexion", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Connexion", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
-->